### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by miketucker** [banool/recreation-gov-campsite-checker#22]
Thank you for putting this tool together! 
Not sure if this is on my end, or if the tool no longer works, but here is the error I'm seeing while running:

```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
```

**Comment by banool** [comment]
I assume this is an error on your end, but I haven't yet checked myself. I'll report back in when I next use the script.

**Comment by andymotta** [comment]
Same issue-- It looks like fakeuseragent is refusing to verify a self-signed certificate in the chain.  Skipping verification worked for me, though I'm not sure that's the best solution: https://github.com/hellysmile/fake-useragent/issues/53#issuecomment-332732039

**Comment by banool** [comment]
I haven't seen this issue come up since, I'm closing this for now.
