### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by Wolfgang51** [banool/recreation-gov-campsite-checker#23]
I've been searching for docs on the api but haven't been able to find anything. Would you be able to point me to the site for the api's docs?

**Comment by banool** [comment]
The site's API has no docs, I just figured it out with the Firefox dev tools for the most part.

**Comment by Wolfgang51** [comment]
Good to know, an unfortunate means to get at their data 🙃. Have you found any good ways to pull the campground "ID"s from somewhere by name?

**Comment by banool** [comment]
Closing this just to keep the issues tracker clean.
