### ISSUE TITLE
Always returns 0 availability

### ISSUE THREAD

**Issue by ccritter** [banool/recreation-gov-campsite-checker#29]
Every time I run the script, even on campsites that have availability shown on the recreation.gov website, I get 0 availability. I think I've pinpointed the issue in the code: When checking for consecutive nights, the range on [line 185](https://github.com/banool/recreation-gov-campsite-checker/blob/8c1518b22973714c6aab9029c262cd10532b7020/camping.py#L185) evaluates to range(0, 0) which will not iterate and produce an empty list for `long_enough_consecutive_ranges`. I'm not sure what the correct area to fix it would be:

(assuming input values of start_date `2021-06-01` and end_date `2021-06-03`)
1. Change the range to `range(0, len(r) - nights + 1)`. EDIT: just tried this, got an `IndexError` on line 190 so I suppose that's not it.
2. Fix the `dates` set in `get_num_available_sites` to include the end_date (possibly by changing the range start from `1` to `0`?):
https://github.com/banool/recreation-gov-campsite-checker/blob/8c1518b22973714c6aab9029c262cd10532b7020/camping.py#L128
Otherwise, the value of the `dates` set will be `{'2021-06-02T00:00:00Z', '2021-06-01T00:00:00Z'}`. This makes `nights` equal 2, which is what I would expect. However, the `desired_available` will only have those two dates (so `len(r)` also equals 2), which causes the above hiccup with the range in `consecutive_nights`.

**Comment by trungnguyencs** [comment]
Yeah the same happened to me

**Comment by ccritter** [comment]
For my use-case (entering a start+end date of desired nights and the park IDs), I seem to have fixed it by changing the `1` to a `0` in the snippet seen in the OP. I have not done any testing to see if this breaks functionality for the "enter wide date range and a number of nights and see if there are any availabilities for that number of nights" use-case.

**Comment by remotesam** [comment]
@ccritter For the basic use case that you mentioned, did you changed line 128 to:
 dates = [end_date - timedelta(days=i) for i in range(1, num_days)] 

Any other change?

**Comment by aries223** [comment]
I am seeing the same issue. Script always returns 0 available even when I verify there are open sites available.

**Comment by aries223** [comment]
Update: I have changed the `1` to a `0` and still get the same "no sites available" issue...

**Comment by ccritter** [comment]
To clarify, this is what I mean by changing 1 to 0 on line 128:
` dates = [end_date - timedelta(days=i) for i in range(0, num_days + 1)] `

**Comment by aries223** [comment]
Yep I have the line exactly like that and still get 0 results:

```
$ sudo python3 camping.py --start-date 2021-05-01 --end-date 2021-05-31 --stdin < parklist.txt
There are no campsites available :(
❌ Lodgepole Campground-Sequoia and Kings Canyon National Park (232461): 0 site(s) available out of 191 site(s)
❌ SUNSET CAMPGROUND (CA) (234752): 0 site(s) available out of 153 site(s)
❌ UPPER PINES (232447): 0 site(s) available out of 240 site(s)
❌ LOWER PINES (232450): 0 site(s) available out of 75 site(s)
❌ NORTH PINES (232449): 0 site(s) available out of 93 site(s)
❌ TUOLUMNE MEADOWS (232448): 0 site(s) available out of 21 site(s)
```

As of right now Lodgepole has ~24 openings within that date range.

**Comment by ccritter** [comment]
Err, I'm on recreation.gov for Lodgepole and I don't see any openings for 31 consecutive nights for that campground. Did you mean to supply a number of nights that you're planning on staying? Because by default, the date range you're asking for means that you want to stay for that entire date range.

https://github.com/banool/recreation-gov-campsite-checker#number-of-nights

**Comment by aries223** [comment]
lol, yep that was it. I was thinking it would return any openings within that time period...
So, it appears to be working then..

**Comment by aries223** [comment]
@ccritter Have you been able to get this to run from cron and somehow notify (other than twitter)?

**Comment by ccritter** [comment]
I've had mine running on cron for a little over a week, notifying me via Matrix if it gets a hit. No luck with availability though yet, the campsites I'm looking at are super booked up. If you're having some other trouble with it besides what we've been diagnosing in this thread, I'd be happy to help (but not here, since this thread should be focused on the issue specified in the original post). You can make a new issue, if you need to.

**Comment by aries223** [comment]
That would be great, making a new issue...

**Comment by banool** [comment]
@ccritter Did you manage to come up with a fix for this issue? I'm more than open to PRs :)

**Comment by ccritter** [comment]
The fix I've been talking about in this thread appears to work for me, but I haven't done much testing for the other use cases. If I get a chance I can make sure it's doing what it's supposed to, but not sure when I'll have a moment to do so.

**Comment by banool** [comment]
Closing this as #32 should've fixed it.
