### ISSUE TITLE
Script is not working for me

### ISSUE THREAD

**Issue by venery99** [banool/recreation-gov-campsite-checker#3]
When I run this script it error 403, forbidden. I have been trying to figure out what the problem is, but I am too new to python:

python3 camping.py --start-date 2019-06-23 --end-date 2019-06-25 7232447
There are campsites available from 2019-06-23 to 2019-06-25!!!
Traceback (most recent call last):
  File "camping.py", line 115, in &lt;module&gt;
    resp_json = send_request(park_id, payload)
  File "camping.py", line 39, in send_request
    resp.status_code, url, resp.text
RuntimeError: ('failedRequest', 'ERROR, 403 code received from https://www.recreation.gov/api/camps/availability/campground/7232447: &lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"&gt;\n&lt;HTML&gt;&lt;HEAD&gt;&lt;META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1"&gt;\n&lt;TITLE&gt;ERROR: The request could not be satisfied&lt;/TITLE&gt;\n&lt;/HEAD&gt;&lt;BODY&gt;\n&lt;H1&gt;403 ERROR&lt;/H1&gt;\n&lt;H2&gt;The request could not be satisfied.&lt;/H2&gt;\n&lt;HR noshade size="1px"&gt;\nRequest blocked.\n\n&lt;BR clear="all"&gt;\n&lt;HR noshade size="1px"&gt;\n&lt;PRE&gt;\nGenerated by cloudfront (CloudFront)\nRequest ID: DmqulFd2PBxlrq4dKFBCiy380B7wv1Lu9WsL8WdiSCkTBwND9A7Wkg==\n&lt;/PRE&gt;\n&lt;ADDRESS&gt;\n&lt;/ADDRESS&gt;\n&lt;/BODY&gt;&lt;/HTML&gt;')"

**Comment by banool** [comment]
See issue #2, I'll go reopen that if this is still occurring.
