### ISSUE TITLE
FakeUserAgentError

### ISSUE THREAD

**Issue by jeffgoldbloom** [banool/recreation-gov-campsite-checker#38]
I'm fairly new to python, but want to try to figure this out. When I run the script, I get the following error:

fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

Can anyone help describe what I should do to fix this?

**Comment by banool** [comment]
Not sure about this one. Given the age of the issue, I'm gonna close it to keep the queue clean, but feel free to re open if you're still having issues.
