### ISSUE TITLE
API Change?

### ISSUE THREAD

**Issue by kabima** [banool/recreation-gov-campsite-checker#51]
I'm a beginner and was very happy when I got this all to work on my RaspberryPi 4 but as of a day or two ago I get a 404 error.

**Comment by kabima** [comment]
Apologies. It appears to have been a corrupted SD card. It's working again. As a side note, the first time I installed this I couldn't get the twitter notifier to work. It turned out to be a twitter library conflict. pip uninstall twitter and pip install python-twitter fixed the issue.

**Comment by banool** [comment]
Hey, glad you figured it out :)
