### ISSUE TITLE
Is the project still working?

### ISSUE THREAD

**Issue by kekec** [banool/recreation-gov-campsite-checker#58]
Hi,

I have downloaded the project and started it. Somehow the script tells me there are no sites available.

`python camping.py --start-date 2023-05-03 --end-date 2023-05-11 --parks 234015`

But looking at the website for [pinnacles ](https://www.recreation.gov/camping/campgrounds/234015) there should be some open spots.

![image](https://user-images.githubusercontent.com/924630/236048979-9dc819d8-1058-48f8-bd72-096f9bebe45b.png)

Is there something wrong?

Paul

**Comment by banool** [comment]
I don't quite have time to look at this right now, but I'd appreciate a community PR to fix this if it is indeed a legit issue.

**Comment by drewcm** [comment]
@keke the command you provided is looking for a single campsite that is available for all dates between 05/03/23 and 05/11/23.  The screenshot you provided does not show a campsite that is available for all those dates.

Multi-day reservations work when I try it, after reviewing recreation.gov to verify availability for these dates:
```
python camping.py --start-date 2023-05-18 --end-date 2023-05-21 --parks 234015
there are campsites available from 2023-05-18 to 2023-05-21!!!
🏕 PINNACLES CAMPGROUND (234015): 1 site(s) available out of 134 site(s)
```

I think this ticket should be closed out.
