### ISSUE TITLE
BUG - type-hint incompatibility in python 3.7

### ISSUE THREAD

**Issue by oregev11** [banool/recreation-gov-campsite-checker#59]
I used python 3.7 as suggested in the README but when running:
 `python camping.py --start-date 2018-07-20 --end-date 2018-07-23 --parks 232448 232450 232447 232770` 
 I got the following error:
`Traceback (most recent call last):
  File "camping.py", line 275, in <module>
    def remove_comments(lines: list[str]) -> list[str]:
TypeError: 'type' object is not subscriptable`

solution can be either:
1) use higher version of python (and update the README)
2) remove the type annotation in line 275 to make it more compatible with earlier python versions:
` def remove_comments(lines: list[str]) -> list[str]:` --> `def remove_comments(lines):`

**Comment by banool** [comment]
Solution 1 sounds good to me! Feel free to make a PR, I don't have much time to work on this currently. Thanks!

**Comment by banool** [comment]
Addressed by mentioning in the comments that 3.9+ is needed: https://github.com/banool/recreation-gov-campsite-checker/pull/60.
