### ISSUE TITLE
STDIN doesn't work per usage

### ISSUE THREAD

**Issue by fireheadman** [banool/recreation-gov-campsite-checker#9]
Attempting to use --stdin < parks.txt
Not working

```
(camp) [root@camp recreation-gov-campsite-checker-master 53]# python camping.py --start-date 2019-07-10 --end-date 2019-07-11 --stdin < parks.txt
usage: camping.py [-h] --start-date START_DATE --end-date END_DATE [--stdin]
                  park [park ...]
camping.py: error: the following arguments are required: park

(camp) [root@camp recreation-gov-campsite-checker-master 54]# python camping.py --start-date 2019-07-10 --end-date 2019-07-11 --stdin park < parks.txt
usage: camping.py [-h] --start-date START_DATE --end-date END_DATE [--stdin]
                  park [park ...]
camping.py: error: argument park: invalid int value: 'park'

(camp) [root@camp recreation-gov-campsite-checker-master 56]# python camping.py --start-date 2019-07-10 --end-date 2019-07-11 --stdin parks.txt
usage: camping.py [-h] --start-date START_DATE --end-date END_DATE [--stdin]
                  park [park ...]
camping.py: error: argument park: invalid int value: 'parks.txt'
```

**Comment by banool** [comment]
What's in `parks.txt`? Feel free to submit a pull request!

**Comment by fireheadman** [comment]
just like the example...

(camp) [root@camp recreation-gov-campsite-checker-master 163]# cat parks.txt
233187
232463
232462

**Comment by banool** [comment]
Knock yourself out my guy, sounds like a good first issue (I just tagged it as such) 😃

**Comment by fireheadman** [comment]
still doesn't work...... if you see the same issue I am explaining, please by all means correct your code so it is functional.

If I am doing something incorrect on the syntax, please let me know what I need to correct.

Thanks

**Comment by banool** [comment]
I'm afk for a few weeks so I'm unable to fix it myself, but I imagine this would be an easy PR. Just put the two arguments in a mutually exclusive group probably. Feel free to try yourself!

**Comment by fireheadman** [comment]
I will wait the few weeks.... no rush on my side.
Am confused on the "two arguments".   If you can provide an example to better explain I can test it out for you.

**Comment by d0n601** [comment]
Not sure if this was fixed with the merge or what, but stdin works fine for me as described in the README

'''
[x@warlab recreation-gov-campsite-checker]$ python camping.py --start-date 2020-07-10 --end-date 2020-07-12 --stdin < parks.txt
There are no campsites available :(
❌ WHITEHORSE CAMPGROUND (234738): 0 site(s) available out of 11 site(s)
'''

Thanks for the script BTW. I almost started to write my own then figured I'd search github first and here we are, exactly what I needed.

**Comment by banool** [comment]
I agree, I think this is fixed. I'm closing this issue for now.
